### ISSUE TITLE
Generate lighter or darker color

### ISSUE THREAD

**Issue by GeReinhart** [MichaelFenwick/Color#5]
Like in http://www.sitepoint.com/javascript-generate-lighter-darker-color/

Would be very useful.

**Comment by MichaelFenwick** [comment]
Something I have been thinking about for a while. It makes sense to support a lighter() and darker() method by changing the Luminance while in HSL space. The question is what arguments that should take, and if it should be linear or perhaps some percentage of its current brightness. Still not sure what to do there, which is why I haven't added it yet. In the meantime, you can convert a Color to an HslColor and set the luminance directly.

**Comment by GeReinhart** [comment]
I was thinking of a percentage as a parameter.
Thanks for the trick with HslColor.
